name: iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  iOS:
    name: Test iOS 
    runs-on: macos-12
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=15.5,name=iPhone 13 Pro Max"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Stepping.xcodeproj" -scheme "SteppingTests" -destination "${{ matrix.destination }}" clean test | xcpretty
