name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@latest
    - uses: tgymnich/setup-swift@v1
      with:
        version: '5.1.3'
    - run: swift build
    - run: swift test
